spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/basicdb
    username: root
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
      dialect:
        org.hibernate.spatial.dialect.postgis.PostgisDialect
      temp:

    database: postgresql
    show-sql: true